object DependencyVersions {
    const val KOTLIN = "1.3.50"
    const val APP_COMPAT = "1.1.0"
    const val MATERIAL = "1.1.0-beta01"
    const val COROUTINES = "1.3.2"
    const val ROOM = "2.2.2"
    const val RECYCLER_VIEW = "1.1.0-alpha06"
    const val NAVIGATION = "2.1.0"
    const val LIFECYCLE = "2.1.0"
    const val CORE_KTX = "1.1.0"
    const val FRAGMENT_KTX = "1.2.0-alpha02"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0-alpha02"
    const val DAGGER = "2.24"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.6.2"
    const val MOSHI = "1.8.0"
    const val MOSHI_CONVERTER = "2.4.0"
    const val COIL = "0.8.0"
    const val LOGGING = "4.2.2"
    const val GROUPIE = "2.7.0"
}